### ISSUE TITLE
Error on update of spec.ts file

### ISSUE THREAD

**Issue by jennifer-shehane** [rubendmatos1985/typescript-cypress#2]
I was trying to get this running and my setup ran into an error as soon as I made changes within `cypress open` to my TypeScript specfile. 

## My project (nothing else!)

`cypress/integration/spec.js`

```js
it('test', () => {
  expect(true).to.be.true
})
```

`cypress/plugins/index.js`

```js
const { typescriptCypressTranspiler } = require('typescript-cypress')

const _module = {
  rules: [
    {
      test: /\.tsx?$/,
      use: [
        {
          loader: 'babel-loader',
          options: {
            presets: [
              ['@babel/preset-env'],
              '@babel/preset-typescript',
              ['@babel/preset-react', { development: true }]
            ],
            plugins: [
              '@babel/plugin-transform-destructuring',
              '@babel/plugin-proposal-object-rest-spread',
              '@babel/plugin-transform-typescript',
              '@babel/plugin-transform-parameters',
              '@babel/plugin-proposal-export-default-from',
              [
                '@babel/plugin-transform-runtime',
                {
                  corejs: 2
                }
              ]
            ]
          }
        }
      ],
      exclude: /node_modules/
    }
  ]
}

module.exports = (on, config) => {
  on('file:preprocessor', typescriptCypressTranspiler(_module))
}
```

`package.json`

```json
{
  "name": "cypress-test",
  "dependencies": {},
  "devDependencies": {
    "cypress": "3.8.3",
    "typescript-cypress": "^1.0.3",
    "webpack": "^4.41.5"
  }
}
```

## During `cypress open`

When I made a change to my `spec.js` file, this error throws

<img width="1347" alt="Screen Shot 2020-01-29 at 5 29 05 PM" src="https://user-images.githubusercontent.com/1271364/73351407-4e695700-42bd-11ea-8550-ea5553747b33.png">

I then closed the running test and was presented with this error. 

![Screen Shot 2020-01-29 at 5 30 30 PM](https://user-images.githubusercontent.com/1271364/73351441-5d500980-42bd-11ea-8070-be1e6d404930.png)

---

I notice there aren't any tests for this plugin and would suggest some tests be written in order to have this plugin featured on the Cypress docs. https://github.com/cypress-io/cypress-documentation/pull/2437

**Comment by coderwaschbaer** [comment]
Hi yes i am receiving the same error. 
    - crashing because of rimraf = fixed
    - hot reloading = fixed
I have already  fixed it. Try installing the plugin again typescript-cypress v1.0.5

**Comment by jennifer-shehane** [comment]
I'm still getting this error when opening my ts file - it's not loading the test. 

<img width="1341" alt="Screen Shot 2020-01-31 at 2 23 16 PM" src="https://user-images.githubusercontent.com/1271364/73521788-4a604500-4435-11ea-8604-1dbf0eabba69.png">
